import { resolveRuntimeSeoConfig } from './settings/load-settings';

export interface LlmsTxtOptions {
  content?: string;
  siteName?: string;
  siteUrl?: string;
}

export function buildLlmsTxtContent(options: LlmsTxtOptions): string {
  if (options.content?.trim()) {
    return options.content.trim();
  }

  const siteName = options.siteName ?? 'This site';
  const siteUrl = options.siteUrl ?? '';
  return `# ${siteName}\n\n> Generated by @seosuite/next\n\n${siteUrl ? `- Site: ${siteUrl}\n` : ''}`;
}

export function createLlmsTxtRoute(options: LlmsTxtOptions = {}) {
  return async function GET(): Promise<Response> {
    const config = await resolveRuntimeSeoConfig();
    const body = buildLlmsTxtContent({
      content: options.content,
      siteName: options.siteName ?? config.siteName,
      siteUrl: options.siteUrl ?? config.siteUrl,
    });

    return new Response(`${body}\n`, {
      headers: { 'Content-Type': 'text/plain; charset=utf-8' },
    });
  };
}
